### ISSUE TITLE
[bug]: App crashes randomly with fatal exception 

### ISSUE THREAD

**Issue by AsterionXeity** [pyoncord/Bunny#115]
### Checklist

- [X] I am able to reproduce the bug with the latest version of Bunny and Discord.
- [X] I've checked that there is no open or closed issue about this bug.
- [X] The title of this issue accurately describes the bug.
- [X] This is not a feature request or a general question.
- [X] This bug can be reproduced consistently and is not caused by a plugin.
- [X] I have read the notes above and ensured that my issue is clear and within this repository.

### Steps to reproduce the bug

I don't know it randomly occurs 
This time I opened the app, sent a message and wanted to reply using a sticker. It's usually right after opening or switching servers. 
The app also takes a few seconds to minutes to load sometimes which is not my connections fault.

### Expected behavior

No crashes?

### Actual behavior

The app crashes.

### Screenshots/Screen recordings

![Screenshot_20241202-113447_LogFox](https://github.com/user-attachments/assets/033fa206-c30c-4d0c-b86b-ca10ad15b137)
Two times since I rebooted around 3am 

### Logs

```shell
FATAL EXCEPTION: mqt_native_modules
Process: io.github.pyoncord.app, PID: 12964
java.lang.NullPointerException
	at com.discord.user_search_worker.UserSearchTransformedUser$Serializer.deserialize(SourceFile:15)
	at com.discord.user_search_worker.UserSearchTransformedUser$Serializer.deserialize(SourceFile:1)
	at Z9.S.d(SourceFile:160)
	at Z9.c.C(SourceFile:6)
	at X9.D0.J(SourceFile:6)
	at X9.D0$b.invoke(SourceFile:7)
	at X9.D0.b0(SourceFile:4)
	at X9.D0.m(SourceFile:20)
	at kotlinx.serialization.encoding.c$a.c(SourceFile:8)
	at X9.t.h(SourceFile:18)
	at X9.a.i(SourceFile:8)
	at X9.a.f(SourceFile:64)
	at X9.a.deserialize(SourceFile:7)
	at Z9.S.d(SourceFile:160)
	at Z9.c.C(SourceFile:6)
	at X9.D0.J(SourceFile:6)
	at X9.D0$b.invoke(SourceFile:7)
	at X9.D0.b0(SourceFile:4)
	at X9.D0.m(SourceFile:20)
	at com.discord.user_search_worker.UserSearchUpdateUsersData$$serializer.deserialize(SourceFile:1)
	at com.discord.user_search_worker.UserSearchUpdateUsersData$$serializer.deserialize(SourceFile:2)
	at Z9.S.d(SourceFile:160)
	at Z9.c.C(SourceFile:6)
	at Z9.b0.a(SourceFile:69)
	at kotlinx.serialization.json.Json.d(SourceFile:11)
	at Y9.d.deserialize(SourceFile:29)
	at Z9.W.C(SourceFile:77)
	at kotlinx.serialization.json.Json.b(SourceFile:31)
	at com.discord.user_search_worker.UserSearchWorker.onMessage(SourceFile:17)
	at com.discord.user_search_worker.UserSearchWorkerManagerModule.onmessage(SourceFile:8)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(SourceFile:153)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(SourceFile:20)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:1)
	at android.os.Looper.loopOnce(Looper.java:245)
	at android.os.Looper.loop(Looper.java:364)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(SourceFile:38)
	at java.lang.Thread.run(Thread.java:1012)
```

### What platform did you produce this issue on?

Android

### Discord version

255.14

### Version

e80ab84-main

### Loader version

BunnyXposed 0.2.5

### Device

Asus ROG phone 6

### OS version

Android 14

### Debug information

**Bunny Debug Info**
> Bunny: e80ab84-main (BunnyXposed 0.2.5)
> Discord: 255.14 (255014)
> React: 18.3.1 (RN 0.74.5-discord-11)
> Hermes: for RN 0.74.5-discord-11 (bcv96)
> System: Android 14 (SDK 34)
> Device: ASUS_AI2201_C (ASUS_AI2201)

**Comment by AsterionXeity** [comment]
Honestly reinstalled the app and don't have the crashing issue. It still gives me an error about the servers though. 
I do also still have the faulty app installed for debugging

**Comment by amsryq** [comment]
Judging by the logs, it seems to be a Discord bug.

**Comment by AsterionXeity** [comment]
> Judging by the logs, it seems to be a Discord bug.

Sad discord releases such an trash app and it still present.
